### ISSUE TITLE
zigbee2mqtt plugin is not starting: Error: SRSP - SYS - version after 6000ms

### ISSUE THREAD

**Issue by aplsms** [danielwelch/hassio-zigbee2mqtt#267]
Hello,

Plugin is failing to start.
The same USB stick is working well on the same hardware with standalone zigbee2mqtt-armhf:1.7.1. i can see /dev/ttyACM1 device from container.

**Versions:** 
zigbee2mqtt version:  dwelch2101/zigbee2mqtt-armhf:1.7.1 (updated yesterday)
HassOS 3.5
Home assistant version : 0.102.2
hardware: raspberry Pi 4b 4Gb

*Stick is /dev/ttyACM1 (not /dev/ttyACM0. /dev/ttyACM0 -- zwave stick)*

**lsusb**:

```
➜  ~ lsusb
...
Bus 001 Device 012: ID 0451:16a8
...
```

**Error log messages**
```2019-11-25T16:42:56: PM2 log: App [npm:0] starting in -fork mode-
2019-11-25T16:42:56: PM2 log: App [npm:0] online
> zigbee2mqtt@1.7.1 start /zigbee2mqtt-1.7.1
> node index.js
zigbee2mqtt:info  2019-11-26T00:42:59: Logging to directory: '/share/zigbee2mqtt/log/2019-11-25.16-42-59'
zigbee2mqtt:info  2019-11-26T00:42:59: Starting zigbee2mqtt version 1.7.1 (commit #unknown)
zigbee2mqtt:info  2019-11-26T00:42:59: Starting zigbee-herdsman...
zigbee2mqtt:error 2019-11-26T00:43:06: Error while starting zigbee-herdsman
zigbee2mqtt:error 2019-11-26T00:43:06: Failed to start zigbee
zigbee2mqtt:error 2019-11-26T00:43:06: Exiting...
zigbee2mqtt:error 2019-11-26T00:43:06: Error: SRSP - SYS - version after 6000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/zigbee2mqtt-1.7.1/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.7.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.7.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm
 
ERR!
 A complete log of this run can be found in:
npm
 
ERR!
     /root/.npm/_logs/2019-11-26T00_43_06_941Z-debug.log
2019-11-25T16:43:09: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-11-25T16:43:09: PM2 log: App [npm:0] starting in -fork mode-
2019-11-25T16:43:09: PM2 log: App [npm:0] online
```
**Config**

```
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://hassio.petrenko.house",
    "user": "zb2mqtt_login",
    "password": "zb2mqtt_password"
  },
  "serial": {
    "port": "/dev/ttyACM1"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {},
  "socat": {
    "enabled": false,
    "master": "pty,raw,echo=0,link=/dev/ttyZ2M,mode=777",
    "slave": "tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5",
    "restartdelay": 1,
    "initialdelay": 1,
    "options": "-d -d",
    "log": false
  },
  "debug": true,
  "zigbee_herdsman_debug": true
}
```

**How to repeat**:
1. install hassio by manual  https://www.home-assistant.io/hassio/installation/
2. upgrade to the latest version
3. install zigbee2mqtt by https://github.com/danielwelch/hassio-zigbee2mqtt
3. apply config
4. press start button.
5. got error message.

Please let me know if you need more information.

**Comment by Dyllaann** [comment]
I have the exact same issue. Yesterday evening everything was working fine.

**Comment by xeac** [comment]
Not sure if my problem is the same, but i can't start the plugin too. I've updated the Home Assistant to 0.102.2 and afterwards zigbee2mqtt plugin to 1.7.1. That's the reason i can't say what causes the issue.
Debug was not successful -> CC2531 USB stick re-flashed, Zigbee2mqtt addon re-installed and re-configured. 

The error message i get is following:
19-11-26 22:23:10 ERROR (SyncWorker_6) [hassio.docker] Can't create container from addon_7ad98f9c_zigbee2mqtt: 404 Client Error: Not Found ("No such image: dwelch2101/zigbee2mqtt-armhf:1.7.1")

**Comment by bmangodt** [comment]
Exact same issue here. Woke up this morning and nothing worked. Worked fine before on 1.7.1...

**Comment by HABuild** [comment]
I ran into the same issue. 
I had just received my cc2531 today, so wasn't really sure. 
I flashed version 1.2 as my first go, and it worked no problems. 
I then went to try version 3.0, and got this issue. I tried a couple reflashes and both hassio versions. 
still the same. 
I just reflashed back to 1.2 and it loaded first go.

**Comment by redahb** [comment]
I had the exact same issue about 3 days ago. I had not updated to HA 102 yet. Strangely, it was fixed by reflashing the same 1.2 firmware that was already on the CC2531 stick.

**Comment by skluthe** [comment]
Having the same issue on a fresh install. Using a HUSBZB-1 for control. Can use HA to discover devices on it so I know the stick works.

**Comment by moustic999** [comment]
same issue here on a complete new install. Any idea about the issue ?

**Comment by RomainD2** [comment]
Hi,

Same issue here, I don't know what happened, but everything was working fine before, for 4 to 5 month.

I don't know what to do to have my zigbee device working again...

Could you help me ?

Thanks

**Comment by BVeldhuijzen** [comment]
I had the same issue. Stopping the plugin, unplugging the USB device and plugging it in again and starting the plugin resolved the issue for me.

**Comment by austrisv** [comment]
omg, same here. plug&unplug the cc from usb did help. Before that did ton of updates/upgrades and restarts and nothing. I think, it started for me when I tried to change the hostname via raspi-config and then it was not starting anymore. Anyways, is solved and feels so good :)

**Comment by BVeldhuijzen** [comment]
> I had the same issue. Stopping the plugin, unplugging the USB device and plugging it in again and starting the plugin resolved the issue for me.

Unfortunately this worked temporarily. At the moment the error is back again, and unplug/plug does not help anymore.

**Comment by mpuff** [comment]
i have the same issue now on the latest 1.9.0

**Comment by myshyak** [comment]
Having same error... Please advice the way around.
zigbee2mqtt:error 2020-01-19 08:33:10: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-01-19 08:33:10: Failed to start zigbee
zigbee2mqtt:error 2020-01-19 08:33:10: Exiting...
zigbee2mqtt:error 2020-01-19 08:33:10: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/zigbee2mqtt-1.9.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:113:32)
    at Generator.next (<anonymous>)
    at /zigbee2mqtt-1.9.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/zigbee2mqtt-1.9.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:4:12)
    at SerialPort.<anonymous> (/zigbee2mqtt-1.9.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:111:49)
    at SerialPort._error (/zigbee2mqtt-1.9.0/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /zigbee2mqtt-1.9.0/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.9.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.9.0 start script.

**Comment by mpuff** [comment]
after some reboots its working again.

**Comment by g8dm8d** [comment]
Had the same problem on a Pi 4.
When proting it from my laptop, i have kept the /dev/tty... pattern path in the config file.
Using the /dev/serial/by-id/... pattern path (as said on the official documentation) solved the problem for me.

**Comment by Dennis650** [comment]
Hi, same Problem here. I noticed it with Zigbee2mqtt 1.8.0. Updated to 1.9.0 but same problem.

**Comment by Dennis650** [comment]
The problem was gone after I removed the stick and reconnected it, for the moment...

**Comment by Dennis650** [comment]
> Hi, same Problem here. I noticed it with Zigbee2mqtt 1.8.0. Updated to 1.9.0 but same problem.

The problem was gone after I removed the stick and reconnected it, for the moment...

**Comment by svenvbins** [comment]
Wonder if there are any updates on this? Received my CC2531 stick today and am running into the same issue as well.

Running:
* Zigbee2mqtt Hass.io Addon 1.9.0
* HassOS 3.8
* Hass.io Supervisor 195
* Home Assistant 0.104.3

Add-on Log:

> 
> zigbee2mqtt:info  2020-01-29 23:32:10: Logging to console and directory: '/share/zigbee2mqtt/log/2020-01-29.23-32-10'
> zigbee2mqtt:info  2020-01-29 23:32:10: Starting zigbee2mqtt version 1.9.0 (commit #unknown)
> zigbee2mqtt:info  2020-01-29 23:32:10: Starting zigbee-herdsman...
> zigbee2mqtt:error 2020-01-29 23:32:23: Error while starting zigbee-herdsman
> zigbee2mqtt:error 2020-01-29 23:32:23: Failed to start zigbee
> zigbee2mqtt:error 2020-01-29 23:32:23: Exiting...
> zigbee2mqtt:error 2020-01-29 23:32:23: Error: SRSP - SYS - version after 6000ms
>     at Timeout._onTimeout (/zigbee2mqtt-1.9.0/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
>     at listOnTimeout (internal/timers.js:531:17)
>     at processTimers (internal/timers.js:475:7)

**Comment by joaomruas** [comment]
Had similar problem.
Tried combinations of: CC2531, CC2530, unplugging, reinstalling, raspberry pi3, raspberry pi4, dev-branch, path "by-id".

Working configuration: pi3b+ with cc2530.

Don't know why and did't try older versions of Hassio neither Zigbee2mqtt.

Decided to Downgrade from raspberry pi4 to 3b+ until further development.

**Comment by Fma965** [comment]
Having the same issue running on a Unraid VM

**Comment by fabsss** [comment]
I do have the same issue. In one night, communication to the sensors stopped working and since a reboot, I get the same error message. I tried to reflash my CC2531 with different firmwares (v1.2, v3...) stick and also tried a second CC2531 with standard CC2531_DEFAULT_20190608 firmware. I also tried the standalone installation of Z2M instead of the hassio-addon but that didn't change the behaviour. 

I sporadically get past the error message when I replug the stick during restart of the addon but afterwards, it doesn't seem to communicate with the devices (i.e. temperature of an environmental sensor stays at the same temperature it was before the problem occured first). I also cannot get into pairing mode.

I tried z2m 1.11, 1.12 and the current edge-release with similar results.

**Comment by unpack8866** [comment]
Had similar problem.
I tried z2m 1.11, 1.12 and the current edge-release with similar results.Very unstable

**Comment by Fma965** [comment]
FWIW: my problem was due to the numpty amazon seller sending me a CC2540 instead of a CC2531

**Comment by michaelsovik** [comment]
Same problem here, worked before the update. Tried every suggestion in this post and nothing. Flashing the stick again did also nothing. Once I start up zigbee2mqtt 1.12.0 the light on my stick goes off and it disappears from the device list.

Pretty annoying to not being able to turn on the lights in these quarantine days..  My stick is a CC2531

**Comment by fabsss** [comment]
Update: I was able to solve the problem by a complete reinstallation of my raspbian incl. new installation of hassio in docker and restore of a previous backup. it seems that some driver issue led to an unresponsive CC2531. I hope that it'll work now and I don't have to do this again anytime soon.

Regards
Fabian

**Comment by joaomruas** [comment]
On my Raspberry pi 3b+ setup after changing CC2530 firmware from normal to source routing I'm having to unplug and re-plug to get around this issue as other stated.

Following fabsss advice will try full re-install one more time...
(I don't use a server due to energy consumption)

Just Wondering why others don't have the same problem. I have reinstalled/re flashed everything... I have 34 devices. Do you also have a high number of devices?

**Comment by fabsss** [comment]
@joaomruas: I only had 4 devices (end devices, no routers) paired by the time. So I don't think it was an issue related to too many devices.

**Comment by dinhchinh82** [comment]
I also got the same issue with the latest version (1.12.2) and also the dev branch. The zigbee2mqtt could not start any more.
ZC: CC2531 default firmware 20190608

Here is debugging log:
https://pastebin.com/1v63PHP3

**Comment by cerw** [comment]
Same problem here on docker :(

**Comment by jeffreyvanhees** [comment]
Same problem! Docker/DSM6 (CC2531), tried everyting. Resetbutton, reconnect stick, using lower versions of Zigbee2MQTT, nothing works.

**Comment by dgreebe** [comment]
I also had problems lately with zigbee2mqtt but because I added 7 devices last couple of days, I though I was hitting a limit or something like that. 
After updating the coordinator with source-routing, I have no issues since then... maybe coinsedence, maybe a bug like other users...

**Comment by jeffreyvanhees** [comment]
> I also had problems lately with zigbee2mqtt but because I added 7 devices last couple of days, I though I was hitting a limit or something like that (have about 45 devices)
> After updating the coordinator with source-routing, I have no issues since then... maybe coinsedence, maybe a bug like other users...

Hmm, I've bought 12 IKEA GU10-bulbs yesterday and was trying to connect them. Everything was working (with 20+ devices), but it suddenly stops working after a couple of hours by showing this message. I have a lot IKEA-bulbs which also act as a router, so I don't think it could be a limitation.

**Comment by dgreebe** [comment]
@jeffreyvanhees that is almost the same issue I had. Bought couple of GU10 bulbs and pairing and all fine.. but suddenly it collapse. Even with about 19 routers (ikea).
I moved to source routing, after couple of hours of frustration and reflashing.. but now... more than 24 hours no issues.

Don't know If its a limitation but with source routing no issues.

**Comment by ThomasHFWright** [comment]
I'm having the same issue. Was working great for about a week with 18 Osram bulbs, but then suddenly the CC2531 could not be connected to. I tried unplugging and replugging the stick, uninstalling the ad-on and reverting all settings and config files to default, device by-id. Can't get any different result!

Using HA 0.111.2, upgrading to 0.111.4 didn't help.
zigbee2mqtt 1.14.0

My logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Socat is DISABLED and not started
2020-06-23T12:39:10: PM2 log: Launching in no daemon mode
2020-06-23T12:39:10: PM2 log: App [npm:0] starting in -fork mode-
2020-06-23T12:39:10: PM2 log: App [npm:0] online
> zigbee2mqtt@1.14.0 start /zigbee2mqtt-1.14.0
> node index.js
zigbee2mqtt:info  2020-06-23 12:39:13: Logging to console and directory: '/share/zigbee2mqtt/log/2020-06-23.12-39-13' filename: log.txt
zigbee2mqtt:info  2020-06-23 12:39:14: Starting zigbee2mqtt version 1.14.0 (commit #unknown)
zigbee2mqtt:info  2020-06-23 12:39:14: Starting zigbee-herdsman...
zigbee2mqtt:error 2020-06-23 12:39:21: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-06-23 12:39:21: Failed to start zigbee
zigbee2mqtt:error 2020-06-23 12:39:21: Exiting...
zigbee2mqtt:error 2020-06-23 12:39:21: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.14.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:72:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.14.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.14.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by traylenator** [comment]
Same as @ThomasHFWright  however not using the v3 firmware but the June2019 v1 release.

**Comment by ciotlosm** [comment]
The above is a problem with either adapter or firmware and not something for the add-on to fix. I recommend using https://github.com/Koenkk/zigbee2mqtt for such issues.

**Comment by aviogit** [comment]
Had exactly the same problem until one minute ago and solved it simply loading the `cdc-acm` kernel module with `sudo modprobe cdc-acm`. This brought up `/dev/ttyACM0` as before the last RPI4 kernel upgrade.

**Comment by c-soft** [comment]
Exactly same issue happened with new Sonoff Zigbee stick, on latest addon.

```
'{"current":0,"energy":0.02,"linkquality":134,"power":0,"power_outage_memory":null,"state":"OFF","voltage":236}'
Zigbee2MQTT:info  2022-01-20 13:16:27: MQTT publish: topic 'zigbee2mqtt/hol_wtyczka_kamera', payload '{"current":0,"energy":0.02,"linkquality":138,"power":0,"power_outage_memory":null,"state":"OFF","voltage":236}'
(node:362) UnhandledPromiseRejectionWarning: Error: SRSP - SYS - version after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
```
