### ISSUE TITLE
Cannot install v1.13.1

### ISSUE THREAD

**Issue by discreetmessage** [danielwelch/hassio-zigbee2mqtt#340]
**zigbee2mqtt add-on version (if edge, please report commit hash):**

**Operating environment (HassOS, Virtual Machine, Device/platform running Hass.io):**

Raspberry Pi 4
HassOS 3.13

**Description of problem:**

Cannot install latest advertised version from within HA. Has latest container been uploaded?

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
hassio | true
host_os | HassOS 3.13
installation_type | Home Assistant
os_name | Linux
os_version | 4.19.114-v7l
python_version | 3.7.7
supervisor | 222
timezone | Europe/Lisbon
version | 0.110.0
virtualenv | false

```

**Your logs from Hass.io**

20-05-20 16:57:17 ERROR (SyncWorker_7) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.13.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:1.13.1 not found: manifest unknown: manifest unknown").

**Comment by P-Verbrugge** [comment]
Same issue here.

**Comment by groenmarsmannetje** [comment]
Same here

**Comment by pjesus00** [comment]
Same here

**Comment by discreetmessage** [comment]
I have a temporary workaround, which is to install the dev version: zigbee2mqtt-edge - this allows me to continue at least, while a fix is deployed.

Still as a developer myself, I question how a release is published with such a seemingly fundamental error/oversight - maybe an review of testing/QA might be in order?

**Comment by apmosss** [comment]
Same here. Same error.

**Comment by Johnwulp** [comment]
Got same issue here:
`20-05-20 18:37:27 ERROR (SyncWorker_8) [supervisor.docker] Can't create container from addon_7ad98f9c_zigbee2mqtt: 404 Client Error: Not Found ("No such image: dwelch2101/zigbee2mqtt-amd64:1.13.1")  `

**Comment by sagitt** [comment]
same

**Comment by mzhovnach** [comment]
Same here: ERROR (SyncWorker_17) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.13.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:1.13.1 not found: manifest unknown: manifest unknown").

**Comment by pterodaktil02** [comment]
same  problen 

> ERROR (SyncWorker_12) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-aarch64:1.13.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-aarch64:1.13.1 not found: manifest unknown: manifest unknown").

**Comment by minnenratta** [comment]
same:

`20-05-20 20:01:01 INFO (SyncWorker_9) [supervisor.docker.interface] Update image dwelch2101/zigbee2mqtt-aarch64:1.13.0 to dwelch2101/zigbee2mqtt-aarch64:1.13.1
20-05-20 20:01:01 INFO (SyncWorker_9) [supervisor.docker.interface] Pull image dwelch2101/zigbee2mqtt-aarch64 tag 1.13.1.
20-05-20 20:01:02 ERROR (SyncWorker_9) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-aarch64:1.13.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-aarch64:1.13.1 not found: manifest unknown: manifest unknown").`

**Comment by emericklaw** [comment]
Dockerhub has not been updated with a 1.13.1 image for both amd64 and armhf.
https://hub.docker.com/r/dwelch2101/zigbee2mqtt-amd64/tags
https://hub.docker.com/r/dwelch2101/zigbee2mqtt-armhf/tags

Can confim that installing the edge version th at @discreetmessage mentioned will get you up and running.

**Comment by justinesmithies** [comment]
I too have the same issue. Hopefully docker images get updated soon.

**Comment by t00** [comment]
Same problem, where edge version expects config files? Beware it overwrites zigbee2mqtt configuration.yaml but when I make changes to it, edge still shows old config.

**Comment by sermayoral** [comment]
Same here
```
20-05-20 22:04:25 ERROR (SyncWorker_12) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.13.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:1.13.1 not found: manifest unknown: manifest unknown").
```

**Comment by cjsteward** [comment]
Same

**Comment by Gio76** [comment]
Same here

**Comment by fedottt** [comment]
stand with you

**Comment by johnjoemorgan** [comment]
Same - Can't install dwelch2101/zigbee2mqtt-armhf:1.13.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:1.13.1 not found: manifest unknown: manifest unknown").

**Comment by Hertizch** [comment]
Same

**Comment by UmbeMont** [comment]
Hi same error 

`20-05-21 06:43:25 INFO (SyncWorker_11) [supervisor.docker.interface] Update image dwelch2101/zigbee2mqtt-armhf:1.13.0 to dwelch2101/zigbee2mqtt-armhf:1.13.1
20-05-21 06:43:25 INFO (SyncWorker_11) [supervisor.docker.interface] Pull image dwelch2101/zigbee2mqtt-armhf tag 1.13.1.
20-05-21 06:43:26 ERROR (SyncWorker_11) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.13.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-armhf:1.13.1 not found: manifest unknown: manifest unknown").
20-05-21 06:43:41 INFO (SyncWorker_7) [supervisor.docker.interface] Restart homeassistant/raspberrypi3-homeassistant
20-05-21 06:44:55 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance`

**Comment by autopower** [comment]
Hello, same error:
20-05-21 06:57:39 ERROR (SyncWorker_4) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-amd64:1.13.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-amd64:1.13.1 not found").

**Comment by kimfisker** [comment]
Same problem here.

**Comment by Kisty** [comment]
Looks like Travis hasn't ran for the 1.13.1 release. This was the last travis build. https://github.com/danielwelch/hassio-zigbee2mqtt/commit/326b758c7af13ab05376beecff93d78812144865

**Comment by Koenkk** [comment]
Seems that something goes wrong with the new Azure pipeline. Temporarily downgraded to 1.13.0 for now.

**Comment by detxm80** [comment]
same problem on x86:
Failed to install addon, Unknown Error, see logs
where are logs?

**Comment by Johnwulp** [comment]
> Seems that something goes wrong with the new Azure pipeline. Temporarily downgraded to 1.13.0 for now.

For some reason the downgrade doesn’t work. My container is running 1.13.0, but it can’t connect to my usb stick. 

`zigbee2mqtt:error 2020-05-21 17:31:28: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:71:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.13.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.13.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.13.0 start script.
npm  `

**Comment by richard-scott** [comment]
@Johnwulp I had to restore just that component from a snapshot.

**Comment by Johnwulp** [comment]
> @Johnwulp I had to restore just that component from a snapshot.

Thanks just did a restore, but issue remains... any other ideas?

**Comment by Johnwulp** [comment]
> > @Johnwulp I had to restore just that component from a snapshot.
> 
> Thanks just did a restore, but issue remains... any other ideas?

I did a full reboot, and it worked again. Don’t know why the container wasn’t able to access the usb stick 🤯

**Comment by Koenkk** [comment]
Should be fixed now

**Comment by Koetjeboeh** [comment]
Can't download the normal version now on a new install, only the edge is visible?

**Comment by to4ko** [comment]
> Should be fixed now

only edge version available. stable one is missing...
![image](https://user-images.githubusercontent.com/45161980/82736318-7d567d80-9d31-11ea-8dc1-f42155d24d23.png)

**Comment by Koenkk** [comment]
@danielwelch could you take a look at this?

**Comment by Koetjeboeh** [comment]
Also it won't discover any device? On the old install everything went by smooth.

**Comment by danielwelch** [comment]
Is it still the case that you can’t see the stable version at all as an installation option? Have you tried removing the repository, restarting, and re-adding it? I ask because this is a first, and the images are all now uploaded correctly on docker hub.

**Comment by Koetjeboeh** [comment]
Removed the plugin, rebooted and added repo again, still the same. 
![IMG_20200523_205306](https://user-images.githubusercontent.com/43536192/82738396-821e3000-9d37-11ea-9138-14ffd8bc3b8d.jpg)

**Comment by IceEyz** [comment]
I just ran into the same issue, this is what the supervisor logs says:
`20-05-23 19:02:12 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt/config.json: does not match regular expression for dictionary value @ data['schema']['experimental']['transmit_power']. Got 'int(-22,19)?'`

**Comment by Koetjeboeh** [comment]
Same as above, but with screenshot
![IMG_20200523_210744](https://user-images.githubusercontent.com/43536192/82738655-8cd9c480-9d39-11ea-8c30-b84dd54ba5c8.jpg)

**Comment by danielwelch** [comment]
Ok, let me roll back that pull request and I’ll rebuild and push as a bug fix release. Thanks.

**Comment by Koetjeboeh** [comment]
> Ok, let me roll back that pull request and I’ll rebuild and push as a bug fix release. Thanks.
> […](#)

Can you update when ready?

**Comment by to4ko** [comment]
1.13.1 just get downloaded and installed

![image](https://user-images.githubusercontent.com/45161980/82754340-ef33d300-9dd4-11ea-8353-e32669c0b95d.png)

**Comment by danielwelch** [comment]
Ok, the breaking change on the master branch has reverted. I also pushed a new bugfix version `1.13.1.1`, but there are no differences between the new version and 1.13.1 other than the updated configuration.

The homeassistant supervisor must parse/inspect `config.json` from the master branch immediately.

**Comment by to4ko** [comment]
@danielwelch trying to update running instance

20-05-24 12:43:28 INFO (SyncWorker_11) [supervisor.docker.interface] Update image dwelch2101/zigbee2mqtt-amd64:1.13.0 to dwelch2101/zigbee2mqtt-amd64:1.13.1.1
20-05-24 12:43:28 INFO (SyncWorker_11) [supervisor.docker.interface] Pull image dwelch2101/zigbee2mqtt-amd64 tag 1.13.1.1.
20-05-24 12:43:30 ERROR (SyncWorker_11) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-amd64:1.13.1.1 -> 404 Client Error: Not Found ("manifest for dwelch2101/zigbee2mqtt-amd64:1.13.1.1 not found: manifest unknown: manifest unknown").

**Comment by danielwelch** [comment]
@to4ko wait until the `1.13.1.1` image is pushed to docker hub

**Comment by Swiftwork** [comment]
@danielwelch not to put any unnecessary pressure, but it still doesn't seem to be pushed to docker hub? Is this normal or has something gone awry again? :)

**Comment by to4ko** [comment]
> @to4ko wait until the `1.13.1.1` image is pushed to docker hub

Thanks! Updated just fine! No issues at all

**Comment by sermayoral** [comment]
@Swiftwork 10 minutes ago it appeared to me. Be patient

**Comment by danielwelch** [comment]
Are we good to close this now?

**Comment by wojciechczyz** [comment]
Strange I am still at 1.13.0 and update does not seem to be detected. I have standard version, not Edge, was only Edge bumped up?

**Comment by minnenratta** [comment]
Update to 1.13.1.1 done. ty.

Am Mo., 25. Mai 2020 um 00:26 Uhr schrieb wojciechczyz <
notifications@github.com>:

**Comment by Koetjeboeh** [comment]
> 
> 
> Are we good to close this now?

Working now! Thanks!

**Comment by hoainamctin** [comment]
I can't install with below error. Is there any idea for this ? Thanks

20-06-03 14:57:42 ERROR (SyncWorker_5) [supervisor.docker.interface] Can't install dwelch2101/zigbee2mqtt-armhf:1.13.1.1 -> 404 Client Error: Not Found ("no such image: dwelch2101/zigbee2mqtt-armhf:1.13.1.1: No such image: dwelch2101/zigbee2mqtt-armhf:1.13.1.1").
