### ISSUE TITLE
Unable to add a new device - Philips Hue P45

### ISSUE THREAD

**Issue by Fridolin34** [danielwelch/hassio-zigbee2mqtt#457]
Hello everybody,

Yesterday my new Phillips Hue bulbs P45 arrived and I tried to connect those lights to my Home Assistant system, but failed.

My system: CC2531 plugged in a Synology, HassIO Docker container and Mosquitto broker and Zigbee2mqtt as installed addons (docker containers as well). Connected are just a couple of Aqara sensors and displaying temperature or humidity readings are just fine.

After switching on the lights, nothing happend. Then I tried to use Touchlink to reset the lamp, hoping that something happens, but in general, does not show anything. Home is empty, no map is shown and also scanning for Touchlink devices brings up nothing. This is not normal, but because I'm getting my sensor values, I did not worry until now. Is there something I could change in order to get a map?

After some time, I read the following lines in my zigbee2mqtt log:
```
Zigbee2MQTT:warn  2020-10-31 11:28:50: Received message from unsupported device with Zigbee model 'LWU001'
Zigbee2MQTT:warn  2020-10-31 11:28:50: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
```

My guessing would be that the light bulb is somehow trying to contact the coordinator, but the device is not supported (yet). Then I tried to follow the instructions to add new devices manually, but I already struggle to find "node_modules/zigbee-herdsman-converters/devices.js".This file is not in my hassio installation, so I assume it is 'hidden' in the zigbee2mqtt addon container. Is that correct? Could somebody please tell me, where to find this container and how to proceed?

Thanks in advance
Fridolin

**Comment by Fridolin34** [comment]
Not sure, whether I'm on the right track or not, but I've added a new file 'devices.js' into '\home-assistant\hass.io\share\zigbee2mqtt'

    {
        zigbeeModel: ['LWU001'],
        model: '9290024406',
        vendor: 'Philips',
        description: 'Philips Hue P45 Light Bulb',
        extend: hue.light_onoff_brightness,
	ota: ota.zigbeeOTA,
    },


info  2020-10-31 12:17:45: 0x001788010940bf8d (0x001788010940bf8d): Not supported (Router)
debug 2020-10-31 12:18:23: Device '0x001788010940bf8d' announced itself
info  2020-10-31 12:18:23: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x001788010940bf8d"},"type":"device_announced"}'
debug 2020-10-31 12:23:37: Received Zigbee message from '0x001788010940bf8d', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16781056,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0
warn  2020-10-31 12:23:37: Received message from unsupported device with Zigbee model 'LWU001'
warn  2020-10-31 12:23:37: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-10-31 12:23:47: Received Zigbee message from '0x001788010940bf8d', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16781056,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0
warn  2020-10-31 12:23:47: Received message from unsupported device with Zigbee model 'LWU001'
warn  2020-10-31 12:23:47: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-10-31 12:23:57: Received Zigbee message from '0x001788010940bf8d', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16781056,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0
warn  2020-10-31 12:23:57: Received message from unsupported device with Zigbee model 'LWU001'
warn  2020-10-31 12:23:57: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-10-31 12:24:07: Received Zigbee message from '0x001788010940bf8d', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16781056,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0
warn  2020-10-31 12:24:07: Received message from unsupported device with Zigbee model 'LWU001'
warn  2020-10-31 12:24:07: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

**Comment by Fridolin34** [comment]
Hmm... did a couple of other steps. 
First I went to https://github.com/danielwelch/hassio-zigbee2mqtt#adding-support-for-new-devices and followed the instructions to obtain an original devices.js file. I've added a similar block from above and now the device is somehow listed correctly after restarting the addon:
info  2020-10-31 13:34:10: 0x001788010940bf8d (0x001788010940bf8d): 9290024406 - Philips Philips Hue P45 Light Bulb (Router)

Then something interesting happend. The device checked, whether there is an update available and found that the firmware it is currently using would be newer than the latest firmware online. Sounds for me that it did not find anything at all, so still somehow fishy.

debug 2020-10-31 13:43:33: Received Zigbee message from '0x001788010940bf8d', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16781056,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0
debug 2020-10-31 13:43:33: Check if update available for '0x001788010940bf8d' (LWU001)
debug 2020-10-31 13:43:33: Is new image available for '0x001788010940bf8d', current '{"fieldControl":0,"manufacturerCode":4107,"imageType":276,"fileVersion":16781056}', latest meta '{"fileVersion":16780804,"fileSize":324910,"url":"http://fds.dc1.philips.com/firmware/ZGB_100B_0114/16780804/100B-0114-01000E04-ConfLightBLE-Lamps-EFR32MG21.zigbee"}'
debug 2020-10-31 13:43:33: Update available for '0x001788010940bf8d': NO
warn  2020-10-31 13:43:33: Firmware on '0x001788010940bf8d' is newer than latest firmware online.
info  2020-10-31 13:43:33: MQTT publish: topic 'zigbee2mqtt/0x001788010940bf8d', payload '{"update_available":false}'
debug 2020-10-31 13:43:43: Received Zigbee message from '0x001788010940bf8d', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16781056,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0
debug 2020-10-31 13:43:53: Received Zigbee message from '0x001788010940bf8d', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16781056,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0
debug 2020-10-31 13:44:03: Received Zigbee message from '0x001788010940bf8d', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16781056,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0


But thats it. I have no clue, whether I need to add something else (e.g. some kind of converter) or what I have to do. The device is still not listed in the list of available devices.

**Comment by JonOve** [comment]
I have exactly the same issue you have, but with the Hue 9290022944.
Made the same steps as you described, but unfortunately without result. I have asked KoenK to add it to the official devices.js file. Now I just wait for the new release and trust the device becomes available.

**Comment by JonOve** [comment]
BTW. In the edge version the device added by KoenK works fine.

**Comment by ciotlosm** [comment]
@Fridolin34 You were on the right track, however it's best to raise device requests here: https://github.com/Koenkk/zigbee2mqtt/issues/new/choose

The add-on just tries to provide some functionality to allow testing if you want to help with device support. 

I will close this as it's been fixed in `edge` by KoenK.

**Comment by Fridolin34** [comment]
Hi you both,

and thanks for answering.

Basically I would appreciate to understand, how it works. I mean, contributing seems more appealing than just consuming. So I thought I could first use the devices.js in the 'share' folder and once everything is running, just hand it over to be officially integrated into the new version.

So, is there any hint, what I could have done to get a proper integration myself?

I just checked edge and downloaded 'zigbee-herdsman-converters-12.0.224', the one used in this version. I cannot find an entry concerning LWU001 in the devices.js. So has it been added otherwise or is it not contained in there?

Thanks again,
Fridolin

**Comment by Fridolin34** [comment]
I've just stopped the normal version of zigbee2mqtt and installed the edge-version. After starting, I still get the same log messages:

warn  2020-11-01 12:25:27: Received message from unsupported device with Zigbee model 'LWU001'
warn  2020-11-01 12:25:27: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
debug 2020-11-01 12:25:37: Received Zigbee message from '0x001788010940bf8d', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16781056,"imageType":276,"manufacturerCode":4107}' from endpoint 11 with groupID 0

At least, it seems to know the name of the device or did I miss to restore something I've changed before?

Thanks,
Fridolin

**Comment by ciotlosm** [comment]
@Fridolin34 using devices.js is not really the recommended approach to add new devices. This was updated with the better `external_converters` method. Unfortunately the add-on in this repo has a bug on that. You can test that method using https://github.com/zigbee2mqtt/hassio-zigbee2mqtt

The add-on however only provides the platform to start the process, the more in depth steps are probably detailed on https://github.com/Koenkk/zigbee2mqtt repo. If you can't find things in the docs, I suggest searching for an older "support device" issue with more comments to get more details on how to write converters & such.
