### ISSUE TITLE
Unknown options ext_pan_id

### ISSUE THREAD

**Issue by andrew-yu** [danielwelch/hassio-zigbee2mqtt#503]
Can't set ext_pan_id option.
Livolo switch configuration required to set configuation options:
```
advanced:
  ext_pan_id: [33,117,141,25,0,75,18,0]
  channel: 26
```
But when the Zigbee2MQTT plugin started the log contains record
`:{"adapter_concurrent":null,"adapter_delay":null,"availability_blacklist":[],"availability_blocklist":[],"availability_passlist":[],"availability_timeout":0,"availability_whitelist":[],"cache_state":true,"cache_state_persistent":true,"cache_state_send_on_startup":true,"channel":26,"elapsed":false,"ext_pan_id":[221,221,221,221,221,221,221,221] ...`

And Supervisor log contains:
`WARNING (MainThread) [supervisor.addons.validate] Unknown options ext_pan_id`

So ext_pan_id set in configuration but ignored as unknown option.

Home Assistant OS 5.9
rpi4-64
Home Assistant 2020.12.1
Zigbee2MQTT version: 1.16.2
Adapter hardware: CC2531
Adapter firmware version: CC2531_DEFAULT_20190608

**Comment by kind3r** [comment]
You have to use `ext_pan_id_string` like so:
```
advanced:
  ext_pan_id_string: '33, 117, 141, 25, 0, 75, 18, 0'
```

Btw, do those switches still require this custom pan_id ? Have you tried pairing them without it ?
I was thinking of getting a few myself to replace my Livolo RF ones, it's one of the reasons I've recently switched to Z2M.
After pairing them could you please report back with some feedback (what works, what does not etc.). Thanks.

**Comment by andrew-yu** [comment]
kind3r, thank you for you advice!

I have two Livolo C701Z, two Livolo C702Z, one Livolo C702SZ and Livolo socket. I connected them to Home Assistant via z2m about year ago. Few months ago i restored my system after microSD fail. Then i got some issues with Livolo devices connection - every few days or week. Then i noticed than i can't setup ext_pan_id. All works great now, but i fixed it only 2 days ago. 

But before my microSD failed, my Livolo devices were very stable for months. And i didn't get any errors about ext_pan_id.

To deal with Livolo permit_join must be enabled. Livolo devices can work only on channel 26. Probably, ext_pan_id should be setup to get stability.

Which experiments with configuration you want? Will try to perform them.

**Comment by kind3r** [comment]
Thanks for the info, my switches will arrive tomorrow so I will test for myself. I already have my network setup on 26, I was just curious if the ext_pan_id is still required or not.
If they worked fine for a year then it's all good, no other experiments required :D

**Comment by wildblue** [comment]
The error message
Unknown option 'ext_pan_id' for Zigbee2mqtt Edge (45df7312_zigbee2mqtt_edge)
Is still showing in my logs as of 2021-11. Please fix that!
